version: '3.4'

services:
  base:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pose_estimation
    volumes:
      - .:/src
      - ./lib:/src/lib

  python:
    image: pose_estimation
    volumes:
      - .:/src
    entrypoint: [ "python" ]